// =========================================
// CHARACTER MEMORY (探索角色记忆)
// 只负责记忆数据的日期、聊天提取、解析校验和 system prompt 文案。
// 页面渲染、按钮事件、API 调用和 IndexedDB 保存仍然留在 App 里。
//
// 函数目录：
//   - pad(num): 数字补零
//   - getTodayKey(now) / getYesterdayKey(now): 获取本地日期 key
//   - getMemory(contactId): 查找某个角色的记忆
//   - ensureMemory(contactId): 没有记忆时创建默认壳数据
//   - getRecord(memory, dateKey): 查找某一天的记忆记录
//   - ensureRecord(memory, dateKey): 没有当天记录时创建默认壳数据
//   - parseMessageDateKey(msg): 从 timestamp 或内容前缀提取日期
//   - collectMessagesForDate(contact, dateKey): 提取某天的可总结聊天
//   - formatMessagesForPrompt(contact, messages): 整理给 AI 的带时间聊天记录
//   - extractJson(rawText): 从 AI 返回里抽出 JSON
//   - normalizeMemoryText(text): 清理记忆文本，不做字数硬截断
//   - parseAiMemory(rawText): 解析并校验 AI 记忆
//   - buildGenerationMessages(contact, dateKey): 生成请求 AI 总结记忆的 messages
//   - getInjectRecords(memory, now): 读取最近 N 天 + 手动长期记住的可注入记录
//   - buildChatPrompt(contactId, now): 生成聊天注入的长期记忆
// =========================================

// ★★★★★ 角色记忆 START：独立工具层 ★★★★★
const CharacterMemory = {
    maxRetry: 2,
    defaultInjectDays: 3,
    maxMemoryCount: 5,

    pad(num) {
        return String(num).padStart(2, '0');
    },

    toDateKey(date) {
        return `${date.getFullYear()}-${this.pad(date.getMonth() + 1)}-${this.pad(date.getDate())}`;
    },

    fromDateKey(dateKey) {
        const [year, month, day] = String(dateKey || '').split('-').map(Number);
        return new Date(year || 1970, (month || 1) - 1, day || 1);
    },

    addDays(date, days) {
        const next = new Date(date);
        next.setHours(0, 0, 0, 0);
        next.setDate(next.getDate() + days);
        return next;
    },

    getTodayKey(now = new Date()) {
        if (typeof TodoContext !== 'undefined' && TodoContext.getTodayKey) {
            return TodoContext.getTodayKey(now);
        }
        const today = new Date(now);
        today.setHours(0, 0, 0, 0);
        return this.toDateKey(today);
    },

    getYesterdayKey(now = new Date()) {
        return this.toDateKey(this.addDays(this.fromDateKey(this.getTodayKey(now)), -1));
    },

    getMemory(contactId) {
        return (STATE.characterMemories || []).find(item => item && item.charId === contactId) || null;
    },

    ensureMemory(contactId) {
        // ★ 记忆按角色保存：第一次点开或打开开关时，先补一份空壳。
        if (!Array.isArray(STATE.characterMemories)) STATE.characterMemories = [];
        let memory = this.getMemory(contactId);
        if (!memory) {
            memory = {
                charId: contactId,
                enabled: false,
                injectDays: this.defaultInjectDays,
                records: [],
                lastAutoGenerateDateKey: '',
                updatedAt: Date.now()
            };
            STATE.characterMemories.push(memory);
        }
        if (!Number.isInteger(Number(memory.injectDays)) || Number(memory.injectDays) < 1) {
            memory.injectDays = this.defaultInjectDays;
        }
        if (!Array.isArray(memory.records)) memory.records = [];
        return memory;
    },

    getRecord(memory, dateKey) {
        return (memory?.records || []).find(record => record && record.dateKey === dateKey) || null;
    },

    ensureRecord(memory, dateKey) {
        let record = this.getRecord(memory, dateKey);
        if (!record) {
            record = {
                id: `memory_day_${dateKey}`,
                dateKey,
                memories: [],
                comment: '',
                generatedAt: null,
                updatedAt: Date.now(),
                error: '',
                isGenerating: false
            };
            memory.records.push(record);
        }
        if (!Array.isArray(record.memories)) record.memories = [];
        record.memories.forEach(item => {
            if (item && typeof item === 'object' && item.alwaysInject !== true) item.alwaysInject = false;
        });
        return record;
    },

    parseMessageDateKey(msg) {
        // ★ 新数据优先用 timestamp；旧数据再从用户消息前缀 [YYYY-MM-DD HH:mm] 兜底。
        const timestamp = String(msg?.timestamp || '').trim();
        const direct = timestamp.match(/^(\d{4}-\d{2}-\d{2})\s+\d{2}:\d{2}/);
        if (direct) return direct[1];

        const content = String(msg?.content || '');
        const prefixed = content.match(/^\[(\d{4}-\d{2}-\d{2})\s+\d{2}:\d{2}\]/);
        if (prefixed) return prefixed[1];

        return '';
    },

    getMessageTimeLabel(msg) {
        const timestamp = String(msg?.timestamp || '').trim();
        const direct = timestamp.match(/^(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})/);
        if (direct) return direct[2];

        const content = String(msg?.content || '');
        const prefixed = content.match(/^\[(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})\]/);
        if (prefixed) return prefixed[2];

        return '--:--';
    },

    getVisibleMessageContentForMemory(msg) {
        // ★★★ 记忆归纳也走统一 AI 可见历史，避免和聊天/心迹的隐藏口径分叉。★★★
        const visible = HistoryVisibility.buildVisibleMessage(msg, {
            preserveTimestamp: false,
            includeImageDescription: true
        });
        return visible ? visible.content : '';
    },

    cleanMessageContent(msg) {
        const content = this.getVisibleMessageContentForMemory(msg);
        return content.replace(/\s+/g, ' ').slice(0, 900);
    },

    collectMessagesForDate(contact, dateKey) {
        return (contact?.history || [])
            .filter(msg => msg && msg.role !== 'system' && msg.content)
            .filter(msg => this.parseMessageDateKey(msg) === dateKey)
            .map(msg => ({
                role: msg.role,
                time: this.getMessageTimeLabel(msg),
                content: this.cleanMessageContent(msg)
            }))
            .filter(msg => msg.content);
    },

    formatMessagesForPrompt(contact, messages) {
        if (!messages.length) return '当天没有可总结的聊天记录。';
        return messages.map(msg => {
            const role = msg.role === 'assistant' ? (contact?.name || '角色') : '用户';
            return `[${msg.time}] ${role}：${msg.content}`;
        }).join('\n');
    },

    extractJson(rawText) {
        const text = String(rawText || '').trim();
        if (!text) throw new Error('AI 返回为空');

        try {
            return JSON.parse(text);
        } catch (error) {
            // ★ 兼容模型偷偷包了 ```json 代码块，或者在 JSON 前后加了废话。
            const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
            if (fenced) return JSON.parse(fenced[1].trim());

            const start = text.indexOf('{');
            const end = text.lastIndexOf('}');
            if (start >= 0 && end > start) {
                return JSON.parse(text.slice(start, end + 1));
            }
            throw error;
        }
    },

    normalizeMemoryText(text) {
        return String(text || '').replace(/\s+/g, ' ').trim();
    },

    parseAiMemory(rawText) {
        const data = this.extractJson(rawText);
        const rawMemories = Array.isArray(data.memories) ? data.memories : [];
        const memories = rawMemories
            .map((item, index) => {
                const text = this.normalizeMemoryText(
                    typeof item === 'string' ? item : (item?.text || item?.memory || '')
                );
                if (!text) return null;
                return {
                    id: item?.id || `memory_item_${Date.now()}_${index}`,
                    text,
                    alwaysInject: item?.alwaysInject === true,
                    updatedAt: Date.now()
                };
            })
            .filter(Boolean)
            .slice(0, this.maxMemoryCount);

        const comment = this.normalizeMemoryText(data.comment || data.note || data.message || '');
        if (!memories.length && !comment) throw new Error('AI 没有返回有效记忆');
        return { memories, comment };
    },

    buildGenerationMessages(contact, dateKey) {
        const dayMessages = this.collectMessagesForDate(contact, dateKey);
        const prompt = [
            '你是 TeleWindy 的角色记忆整理器，要根据某一天的聊天记录，为该角色整理对用户的长期记忆。',
            '请只返回 JSON，不要 Markdown，不要解释。',
            '',
            'JSON 格式必须是：',
            '{"memories":["30字内记忆1","30字内记忆2"],"comment":"20字内角色寄语"}',
            '',
            '硬性要求：',
            '- memories 最多 5 条。',
            '- 每条 memory 30 字以内。',
            '- comment 20 字以内。',
            '- 不要输出 Markdown。',
            '- 不要输出解释。',
            '- 只输出 JSON。',
            '- 不要编造聊天记录中没有的信息。',
            '- 优先保留任务进展、用户状态、重要事实、关系变化、承诺、身体状况、压力来源。',
            '- 尽量不要在记忆中称用户为“用户”，而是使用用户的名字，或角色对用户的称谓',
            '',
            `日期：${dateKey}`,
            '',
            '【角色信息】',
            `角色名：${contact?.name || '未知角色'}`,
            contact?.prompt || '暂无角色设定。',
            '',
            '【当天聊天记录】',
            this.formatMessagesForPrompt(contact, dayMessages)
        ].join('\n');

        return [{ role: 'system', content: prompt }];
    },

    getInjectRecords(memory, now = new Date()) {
        if (!memory || memory.enabled !== true) return [];
        const injectDays = Math.max(1, Number.parseInt(memory.injectDays, 10) || this.defaultInjectDays);
        const today = this.fromDateKey(this.getTodayKey(now));
        const minDate = this.addDays(today, -injectDays);
        const maxDate = this.addDays(today, -1);

        return (memory.records || [])
            // ★ 最近 N 天照常全量注入；更早日期只带用户手动“长期记住”的单条记忆。
            .filter(record => {
                if (!record || !Array.isArray(record.memories) || !record.memories.length) return false;
                const date = this.fromDateKey(record.dateKey);
                const inRecentRange = date >= minDate && date <= maxDate;
                return inRecentRange || record.memories.some(item => item && typeof item === 'object' && item.alwaysInject === true);
            })
            .map(record => {
                const date = this.fromDateKey(record.dateKey);
                const inRecentRange = date >= minDate && date <= maxDate;
                return {
                    ...record,
                    memories: inRecentRange
                        ? record.memories
                        : record.memories.filter(item => item && typeof item === 'object' && item.alwaysInject === true)
                };
            })
            .sort((a, b) => a.dateKey.localeCompare(b.dateKey));
    },

    buildChatPrompt(contactId, now = new Date()) {
        const memory = this.getMemory(contactId);
        const records = this.getInjectRecords(memory, now);
        if (!records.length) return '';

        const injectDays = Math.max(1, Number.parseInt(memory.injectDays, 10) || this.defaultInjectDays);
        const lines = [
            '# 过往记忆',
            `以下是你近期的记忆内容。`
        ];

        records.forEach(record => {
            lines.push('', record.dateKey);
            record.memories.forEach(item => {
                const text = typeof item === 'string' ? item : item?.text;
                if (text) lines.push(`- ${text}`);
            });
        });

        return lines.join('\n');
    }
};
// ★★★★★ 角色记忆 END：独立工具层 ★★★★★
